
name = "leaf-notes-backend"
main = "src/worker.js"
compatibility_date = "2024-04-05"

[durable_objects]
bindings = [
  { name = "NOTES_ROOM", class_name = "NotesBackend" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["NotesBackend"]
